language: java

addons:
  sonarcloud:
    organization: "jafl-github"

script:
  - "mvn dependency:tree"
  - "mvn cobertura:cobertura"
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
